-- ============================================================
-- Atlas Géopolitique — chargement des données OWID (référence figée)
-- Généré automatiquement depuis les données extraites de l'artifact.
-- Sûr à re-exécuter : upserts uniquement, ne touche à aucune donnée
-- que tu as saisie ou modifiée toi-même (fiches pays, dossiers...).
-- À exécuter APRÈS schema_v1..v7.
-- ============================================================

-- Pays de référence (n'écrase jamais une ligne existante)
insert into public.countries (id, name_fr, continent, capital) values ('ZWE', 'Zimbabwe', 'Africa', 'Harare') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ZMB', 'Zambie', 'Africa', 'Lusaka') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('YEM', 'Yémen', 'Asia', 'Sanaa') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('VNM', 'Vietnam', 'Asia', 'Hanoï') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('VEN', 'Venezuela', 'South America', 'Caracas') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('VAT', 'Vatican', 'Europe', 'Rome') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('VUT', 'Vanuatu', 'Oceania', 'Port-Vila') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('UZB', 'Ouzbékistan', 'Asia', 'Tachkent') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('URY', 'Uruguay', 'South America', 'Montevideo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('FSM', 'Micronésie', 'Oceania', 'Palikir') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MHL', 'Îles Marshall', 'Oceania', 'Majuro') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('USA', 'États-Unis', 'North America', 'Washington, D.C.') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GBR', 'Royaume-Uni', 'Europe', 'Hamilton') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ARE', 'Émirats arabes unis', 'Asia', 'Abou Dabi') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('UKR', 'Ukraine', 'Europe', 'Kiev') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('UGA', 'Ouganda', 'Africa', 'Kampala') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TKM', 'Turkménistan', 'Asia', 'Achgabat') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TUR', 'Turquie', 'Asia', 'Ankara') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TUN', 'Tunisie', 'Africa', 'Tunis') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TTO', 'Trinité-et-Tobago', 'North America', 'Port-d''Espagne') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TON', 'Tonga', 'Oceania', 'Nuku''alofa') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TGO', 'Togo', 'Africa', 'Lomé') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TLS', 'Timor oriental', 'Asia', 'Dili') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('THA', 'Thaïlande', 'Asia', 'Bangkok') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TZA', 'Tanzanie', 'Africa', 'Dodoma') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TJK', 'Tadjikistan', 'Asia', 'Douchanbé') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TWN', 'Taïwan', 'Asia', 'Taipei') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SYR', 'Syrie', 'Asia', 'Damas') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CHE', 'Suisse', 'Europe', 'Berne') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SWE', 'Suède', 'Europe', 'Stockholm') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SWZ', 'Eswatini', 'Africa', 'Mbabane') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SUR', 'Suriname', 'South America', 'Paramaribo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SSD', 'Soudan du Sud', 'Africa', 'Djouba') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SDN', 'Soudan', 'Africa', 'Khartoum') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LKA', 'Sri Lanka', 'Asia', 'Colombo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ESP', 'Espagne', 'Europe', 'Madrid') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KOR', 'Corée du Sud', 'Asia', 'Séoul') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ZAF', 'Afrique du Sud', 'Africa', 'Bloemfontein') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SOM', 'Somalie', 'Africa', 'Mogadiscio') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SLB', 'Îles Salomon', 'Oceania', 'Honiara') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SVK', 'Slovaquie', 'Europe', 'Bratislava') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SVN', 'Slovénie', 'Europe', 'Ljubljana') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SGP', 'Singapour', 'Asia', 'Singapour') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SLE', 'Sierra Leone', 'Africa', 'Freetown') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SYC', 'Seychelles', 'Seven seas (open ocean)', 'Victoria') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SRB', 'Serbie', 'Europe', 'Belgrade') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SEN', 'Sénégal', 'Africa', 'Dakar') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SAU', 'Arabie saoudite', 'Asia', 'Riyad') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('STP', 'Sao Tomé-et-Principe', 'Africa', 'São Tomé') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SMR', 'Saint-Marin', 'Europe', 'Saint-Marin') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('WSM', 'Samoa', 'Oceania', 'Apia') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('VCT', 'Saint-Vincent-et-les-Grenadines', 'North America', 'Kingstown') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LCA', 'Sainte-Lucie', 'North America', 'Castries') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KNA', 'Saint-Christophe-et-Niévès', 'North America', 'Basseterre') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('RWA', 'Rwanda', 'Africa', 'Kigali') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('RUS', 'Russie', 'Europe', 'Moscou') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ROU', 'Roumanie', 'Europe', 'Bucarest') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('QAT', 'Qatar', 'Asia', 'Doha') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PRT', 'Portugal', 'Europe', 'Lisbonne') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('POL', 'Pologne', 'Europe', 'Varsovie') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PHL', 'Philippines', 'Asia', 'Manille') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PER', 'Pérou', 'South America', 'Lima') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PRY', 'Paraguay', 'South America', 'Asunción') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PNG', 'Papouasie-Nouvelle-Guinée', 'Oceania', 'Port Moresby') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PAN', 'Panama', 'North America', 'Panama') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PLW', 'Palaos', 'Oceania', 'Ngerulmud') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PAK', 'Pakistan', 'Asia', 'Islamabad') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('OMN', 'Oman', 'Asia', 'Mascate') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NOR', 'Norvège', 'Europe', 'Oslo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('PRK', 'Corée du Nord', 'Asia', 'Pyongyang') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NGA', 'Nigeria', 'Africa', 'Abuja') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NER', 'Niger', 'Africa', 'Niamey') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NIC', 'Nicaragua', 'North America', 'Managua') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NZL', 'Nouvelle-Zélande', 'Oceania', 'Wellington') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NLD', 'Pays-Bas', 'Europe', 'Amsterdam') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NPL', 'Népal', 'Asia', 'Katmandou') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NRU', 'Nauru', 'Oceania', null) on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('NAM', 'Namibie', 'Africa', 'Windhoek') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MOZ', 'Mozambique', 'Africa', 'Maputo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MAR', 'Maroc', 'Africa', 'Rabat') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ESH', 'Sahara occidental', 'Africa', null) on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MNE', 'Monténégro', 'Europe', 'Podgorica') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MNG', 'Mongolie', 'Asia', 'Oulan-Bator') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MDA', 'Moldavie', 'Europe', 'Chișinău') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MCO', 'Monaco', 'Europe', 'Monaco') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MEX', 'Mexique', 'North America', 'Mexico') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MUS', 'Maurice', 'Seven seas (open ocean)', 'Port-Louis') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MRT', 'Mauritanie', 'Africa', 'Nouakchott') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MLT', 'Malte', 'Europe', 'La Valette') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MLI', 'Mali', 'Africa', 'Bamako') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MDV', 'Maldives', 'Seven seas (open ocean)', 'Malé') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MYS', 'Malaisie', 'Asia', 'Kuala Lumpur') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MWI', 'Malawi', 'Africa', 'Lilongwe') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MDG', 'Madagascar', 'Africa', 'Antananarivo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MKD', 'Macédoine du Nord', 'Europe', 'Skopje') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LUX', 'Luxembourg', 'Europe', 'Luxembourg') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LTU', 'Lituanie', 'Europe', 'Vilnius') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LIE', 'Liechtenstein', 'Europe', 'Vaduz') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LBY', 'Libye', 'Africa', 'Tripoli') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LBR', 'Liberia', 'Africa', 'Monrovia') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LSO', 'Lesotho', 'Africa', 'Maseru') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LBN', 'Liban', 'Asia', 'Beyrouth') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LVA', 'Lettonie', 'Europe', 'Riga') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('LAO', 'Laos', 'Asia', 'Vientiane') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KGZ', 'Kirghizistan', 'Asia', 'Bishkek') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KWT', 'Koweït', 'Asia', 'Koweït') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KIR', 'Kiribati', 'Oceania', 'Tarawa') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KEN', 'Kenya', 'Africa', 'Nairobi') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KAZ', 'Kazakhstan', 'Asia', 'Astana') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('JOR', 'Jordanie', 'Asia', 'Amman') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('JPN', 'Japon', 'Asia', 'Tokyo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('JAM', 'Jamaïque', 'North America', 'Kingston') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ITA', 'Italie', 'Europe', 'Cité du Vatican') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ISR', 'Israël', 'Asia', 'Jérusalem') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('IRL', 'Irlande', 'Europe', 'Dublin') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('IRQ', 'Irak', 'Asia', 'Bagdad') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('IRN', 'Iran', 'Asia', 'Téhéran') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('IDN', 'Indonésie', 'Asia', 'Jakarta') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('IND', 'Inde', 'Asia', 'New Delhi') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ISL', 'Islande', 'Europe', 'Reykjavík') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('HUN', 'Hongrie', 'Europe', 'Budapest') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('HND', 'Honduras', 'North America', 'Tegucigalpa') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('HTI', 'Haïti', 'North America', 'Port-au-Prince') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GUY', 'Guyana', 'South America', 'Georgetown') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GNB', 'Guinée-Bissau', 'Africa', 'Bissau') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GIN', 'Guinée', 'Africa', 'Conakry') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GTM', 'Guatemala', 'North America', 'Guatemala') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GRD', 'Grenade', 'North America', 'Saint-Georges') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GRC', 'Grèce', 'Europe', 'Athènes') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GHA', 'Ghana', 'Africa', 'Accra') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('DEU', 'Allemagne', 'Europe', 'Berlin') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GEO', 'Géorgie', 'Asia', 'Tbilissi') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GMB', 'Gambie', 'Africa', 'Banjul') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GAB', 'Gabon', 'Africa', 'Libreville') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('FRA', 'France', 'Europe', 'Paris') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('FIN', 'Finlande', 'Europe', 'Helsinki') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('FJI', 'Fidji', 'Oceania', 'Suva') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ETH', 'Éthiopie', 'Africa', 'Addis-Abeba') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('EST', 'Estonie', 'Europe', 'Tallinn') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ERI', 'Érythrée', 'Africa', 'Asmara') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('GNQ', 'Guinée équatoriale', 'Africa', 'Ciudad de la Paz') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('SLV', 'Salvador', 'North America', 'San Salvador') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('EGY', 'Égypte', 'Africa', 'Le Caire') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ECU', 'Équateur', 'South America', 'Quito') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('DOM', 'République dominicaine', 'North America', 'Santo Domingo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('DMA', 'Dominique', 'North America', 'Roseau') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('DJI', 'Djibouti', 'Africa', 'Djibouti') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('DNK', 'Danemark', 'Europe', 'Copenhague') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CZE', 'Tchéquie', 'Europe', 'Prague') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CYP', 'Chypre', 'Asia', 'Nicosie') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CUB', 'Cuba', 'North America', 'La Havane') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('HRV', 'Croatie', 'Europe', 'Zagreb') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CIV', 'Côte d''Ivoire', 'Africa', 'Yamoussoukro') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CRI', 'Costa Rica', 'North America', 'San José') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('COD', 'République démocratique du Congo', 'Africa', 'Kinshasa') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('COG', 'Congo', 'Africa', 'Brazzaville') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('COM', 'Comores', 'Africa', 'Moroni') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('COL', 'Colombie', 'South America', 'Bogota') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CHN', 'Chine', 'Asia', 'Pékin') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CHL', 'Chili', 'South America', 'Santiago') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TCD', 'Tchad', 'Africa', 'N''Djamena') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CAF', 'République centrafricaine', 'Africa', 'Bangui') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CPV', 'Cap-Vert', 'Africa', 'Praia') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CAN', 'Canada', 'North America', 'Ottawa') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('CMR', 'Cameroun', 'Africa', 'Yaoundé') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('KHM', 'Cambodge', 'Asia', 'Phnom Penh') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('MMR', 'Birmanie', 'Asia', 'Naypyidaw') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BDI', 'Burundi', 'Africa', 'Gitega') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BFA', 'Burkina Faso', 'Africa', 'Ouagadougou') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BGR', 'Bulgarie', 'Europe', 'Sofia') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BRN', 'Brunei', 'Asia', 'Bandar Seri Begawan') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BRA', 'Brésil', 'South America', 'Brasília') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BWA', 'Botswana', 'Africa', 'Gaborone') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BIH', 'Bosnie-Herzégovine', 'Europe', 'Sarajevo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BOL', 'Bolivie', 'South America', 'Sucre') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BTN', 'Bhoutan', 'Asia', 'Thimphou') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BEN', 'Bénin', 'Africa', 'Porto-Novo') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BLZ', 'Belize', 'North America', 'Belmopan') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BEL', 'Belgique', 'Europe', 'Bruxelles') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BLR', 'Biélorussie', 'Europe', 'Minsk') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BRB', 'Barbade', 'North America', 'Bridgetown') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BGD', 'Bangladesh', 'Asia', 'Dhaka') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BHR', 'Bahreïn', 'Asia', 'Manama') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('BHS', 'Bahamas', 'North America', 'Nassau') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('AZE', 'Azerbaïdjan', 'Asia', 'Bakou') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('AUT', 'Autriche', 'Europe', 'Vienne') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('AUS', 'Australie', 'Oceania', 'Canberra') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ARM', 'Arménie', 'Asia', 'Erevan') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ARG', 'Argentine', 'South America', 'Buenos Aires') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ATG', 'Antigua-et-Barbuda', 'North America', 'Saint John''s') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('AGO', 'Angola', 'Africa', 'Luanda') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('AND', 'Andorre', 'Europe', 'Andorre-la-Vieille') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('DZA', 'Algérie', 'Africa', 'Alger') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('ALB', 'Albanie', 'Europe', 'Tirana') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('AFG', 'Afghanistan', 'Asia', 'Kabul') on conflict (id) do nothing;
insert into public.countries (id, name_fr, continent, capital) values ('TUV', 'Tuvalu', 'Oceania', 'Funafuti') on conflict (id) do nothing;

-- Catégories et indicateurs OWID
insert into public.indicator_categories (id, label, position) values ('demographie', 'Démographie', 0) on conflict (id) do update set label = excluded.label, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('population', 'demographie', 'Population', 'habitants', 0, 0) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('esperance_vie', 'demographie', 'Espérance de vie à la naissance', 'années', 1, 1) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('fecondite', 'demographie', 'Taux de fécondité', 'enfants / femme', 2, 2) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('age_median', 'demographie', 'Âge médian', 'années', 1, 3) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('urbanisation', 'demographie', 'Taux d''urbanisation', '% de la population', 1, 4) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicator_categories (id, label, position) values ('economie', 'Économie', 1) on conflict (id) do update set label = excluded.label, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('pib', 'economie', 'PIB', '$ international (prix constants)', 0, 0) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('pib_par_habitant', 'economie', 'PIB par habitant', '$ international / hab.', 0, 1) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('idh', 'economie', 'Indice de développement humain (IDH)', 'indice (0-1)', 3, 2) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('chomage', 'economie', 'Taux de chômage', '% de la population active', 1, 3) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('gini', 'economie', 'Indice de Gini (inégalités de revenu)', 'indice (0-1)', 3, 4) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('pauvrete_extreme', 'economie', 'Pauvreté extrême (seuil 3,00 $/jour)', '% de la population', 1, 5) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicator_categories (id, label, position) values ('energie', 'Énergie & environnement', 2) on conflict (id) do update set label = excluded.label, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('co2_total', 'energie', 'Émissions de CO2 (total)', 'Mt CO2 / an', 1, 0) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('co2_par_habitant', 'energie', 'Émissions de CO2 par habitant', 't CO2 / hab. / an', 2, 1) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('ges_par_habitant', 'energie', 'Gaz à effet de serre par habitant', 't CO2eq / hab. / an', 2, 2) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('energie_par_habitant', 'energie', 'Consommation d''énergie par habitant', 'kWh / hab. / an', 0, 3) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('part_renouvelables', 'energie', 'Part des énergies renouvelables', '% de l''énergie', 1, 4) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('part_fossile', 'energie', 'Part des énergies fossiles', '% de l''énergie', 1, 5) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('part_charbon', 'energie', 'Part du charbon', '% de l''énergie', 1, 6) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('part_gaz', 'energie', 'Part du gaz naturel', '% de l''énergie', 1, 7) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('part_petrole', 'energie', 'Part du pétrole', '% de l''énergie', 1, 8) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('part_nucleaire', 'energie', 'Part du nucléaire', '% de l''énergie', 1, 9) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicator_categories (id, label, position) values ('militaire', 'Militaire', 3) on conflict (id) do update set label = excluded.label, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('mil_pct_pib', 'militaire', 'Dépenses militaires (% du PIB)', '% du PIB', 1, 0) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('mil_depenses', 'militaire', 'Dépenses militaires (valeur absolue)', '$ US constants (2023)', 0, 1) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('effectifs_armee_pct', 'militaire', 'Effectifs des forces armées', '% de la population', 2, 2) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicator_categories (id, label, position) values ('democratie', 'Démocratie & gouvernance', 4) on conflict (id) do update set label = excluded.label, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('democratie_electorale', 'democratie', 'Indice de démocratie électorale (V-Dem)', 'indice (0-1)', 3, 0) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('democratie_liberale', 'democratie', 'Indice de démocratie libérale (V-Dem)', 'indice (0-1)', 3, 1) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('corruption_ipc', 'democratie', 'Indice de perception de la corruption (Transparency Intl.)', 'indice (0-100, 100 = très intègre)', 0, 2) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicator_categories (id, label, position) values ('commerce', 'Commerce & influence', 5) on conflict (id) do update set label = excluded.label, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('commerce_pct_pib', 'commerce', 'Commerce total (exports + imports, % du PIB)', '% du PIB', 1, 0) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;
insert into public.indicators (id, category_id, label, unit, decimals, position) values ('ide_entrant_pct_pib', 'commerce', 'Investissements directs étrangers nets entrants', '% du PIB', 2, 1) on conflict (id) do update set category_id = excluded.category_id, label = excluded.label, unit = excluded.unit, decimals = excluded.decimals, position = excluded.position;

-- Valeurs par pays/année
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'AFG', 42647502, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib', 'AFG', 53303471617, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'AFG', 10.8, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'AFG', 0.25, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'AFG', 0.94, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'AFG', 925, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib_par_habitant', 'AFG', 1250, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_pct_pib', 'AFG', 1.8, 2021) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'AFG', 0.42, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_electorale', 'AFG', 0.069, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_liberale', 'AFG', 0.018, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('corruption_ipc', 'AFG', 17, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('commerce_pct_pib', 'AFG', 83.8, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'AFG', 66, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'AFG', 4.84, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'AFG', 16.9, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'AFG', 25.9, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('chomage', 'AFG', 13.4, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'AFG', 0.496, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'ALB', 2791756, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib', 'ALB', 36171005594, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'ALB', 4.4, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'ALB', 1.59, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'ALB', 2.4, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'ALB', 9168, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib_par_habitant', 'ALB', 12956, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_pct_pib', 'ALB', 2, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_depenses', 'ALB', 568103900, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'ALB', 0.28, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_electorale', 'ALB', 0.484, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_liberale', 'ALB', 0.382, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('corruption_ipc', 'ALB', 42, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('commerce_pct_pib', 'ALB', 79.5, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ide_entrant_pct_pib', 'ALB', 6.06, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'ALB', 79.6, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'ALB', 1.35, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'ALB', 36.3, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'ALB', 58.9, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('chomage', 'ALB', 10.9, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pauvrete_extreme', 'ALB', 0.3, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('gini', 'ALB', 0.294, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'ALB', 0.81, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'DZA', 46814302, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib', 'DZA', 595820067103, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'DZA', 198.2, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'DZA', 4.23, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'DZA', 5.9, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'DZA', 16237, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_renouvelables', 'DZA', 0.2, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_fossile', 'DZA', 99.8, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_charbon', 'DZA', 0.2, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_gaz', 'DZA', 66.5, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_petrole', 'DZA', 33, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_nucleaire', 'DZA', 0, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib_par_habitant', 'DZA', 12727, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_pct_pib', 'DZA', 8.8, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_depenses', 'DZA', 24128442000, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'DZA', 0.74, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_electorale', 'DZA', 0.265, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_liberale', 'DZA', 0.126, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('corruption_ipc', 'DZA', 34, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('commerce_pct_pib', 'DZA', 39, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ide_entrant_pct_pib', 'DZA', 0.46, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'DZA', 76.3, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'DZA', 2.77, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'DZA', 28.2, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'DZA', 75.8, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('chomage', 'DZA', 11.6, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'DZA', 0.763, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'AND', 81955, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'AND', 0.4, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'AND', 5.18, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'AND', 6.48, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'AND', 84, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'AND', 1.08, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'AND', 43.2, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'AND', 88.9, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'AND', 0.913, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'AGO', 37885854, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib', 'AGO', 158346237030, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'AGO', 22.3, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'AGO', 0.59, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'AGO', 4.21, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'AGO', 2660, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib_par_habitant', 'AGO', 4180, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_pct_pib', 'AGO', 1.4, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_depenses', 'AGO', 1263380500, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'AGO', 0.35, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_electorale', 'AGO', 0.344, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_liberale', 'AGO', 0.163, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('corruption_ipc', 'AGO', 32, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('commerce_pct_pib', 'AGO', 34.6, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ide_entrant_pct_pib', 'AGO', 0.94, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'AGO', 64.6, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'AGO', 5.12, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'AGO', 16.5, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'AGO', 71.5, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('chomage', 'AGO', 14.1, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'AGO', 0.616, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'ATG', 93782, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'ATG', 0.7, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'ATG', 7.09, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'ATG', 7.72, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'ATG', 33242, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'ATG', 0, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'ATG', 77.6, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'ATG', 1.58, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'ATG', 35.5, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'ATG', 24.3, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'ATG', 0.851, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'ARG', 45696153, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib', 'ARG', 854914363923, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'ARG', 171.1, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'ARG', 3.74, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'ARG', 9.12, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'ARG', 21514, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_renouvelables', 'ARG', 14.8, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_fossile', 'ARG', 82.6, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_charbon', 'ARG', 1, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_gaz', 'ARG', 46.8, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_petrole', 'ARG', 34.8, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('part_nucleaire', 'ARG', 2.6, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib_par_habitant', 'ARG', 18709, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_pct_pib', 'ARG', 0.6, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_depenses', 'ARG', 3731044900, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'ARG', 0.23, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_electorale', 'ARG', 0.69, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_liberale', 'ARG', 0.524, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('corruption_ipc', 'ARG', 37, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('commerce_pct_pib', 'ARG', 30.4, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ide_entrant_pct_pib', 'ARG', 0.46, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'ARG', 77.4, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'ARG', 1.5, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'ARG', 32.1, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'ARG', 92.4, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('chomage', 'ARG', 7.1, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('idh', 'ARG', 0.865, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('population', 'ARM', 2973843, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib', 'ARM', 39721734780, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_total', 'ARM', 7.4, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('co2_par_habitant', 'ARM', 2.5, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ges_par_habitant', 'ARM', 3.47, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('energie_par_habitant', 'ARM', 16739, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('pib_par_habitant', 'ARM', 13357, 2022) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_pct_pib', 'ARM', 6.1, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('mil_depenses', 'ARM', 1645807200, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('effectifs_armee_pct', 'ARM', 1.63, 2020) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_electorale', 'ARM', 0.614, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('democratie_liberale', 'ARM', 0.371, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('corruption_ipc', 'ARM', 47, 2024) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('commerce_pct_pib', 'ARM', 101.7, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('ide_entrant_pct_pib', 'ARM', 2.07, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('esperance_vie', 'ARM', 75.7, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('fecondite', 'ARM', 1.71, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('age_median', 'ARM', 35.8, 2023) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
insert into public.indicator_values (indicator_id, country_id, value, year) values ('urbanisation', 'ARM', 65.9, 2025) on conflict (indicator_id, country_id) do update set value = excluded.value, year = excluded.year;
